name: budget_smart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  intl: ^0.17.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png  # Replace with your actual asset path

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Regular.ttf
        - asset: assets/Poppins-Bold.ttf
          weight: 700
